### ISSUE TITLE
Incompatibility with Mini Tardis

### ISSUE THREAD

**Issue by GrayStriped** [ThreeTAG/Palladium#108]
Installing Palladium prevents resources for the mod "Mini Tardis" from loading. Specifically, Minecraft will say "Resource reload failed". Pictures attached are with and without Palladium.
![2024-03-18_22 17 19](https://github.com/ThreeTAG/Palladium/assets/44683183/8279b2fe-b9b8-4fa8-8410-b18109985e09)
![2024-03-18_22 19 02](https://github.com/ThreeTAG/Palladium/assets/44683183/7678c4ed-17ec-4f51-ab16-9ae51e0d844b)

**Comment by PierogiPL** [comment]
Does that happen with just Palladium? Based on testing I did, it was that one KubeJS dependency that caused it.

**Comment by Lucraft** [comment]
Can you send a log file with Mini Tardis and Palladium installed?

**Comment by GrayStriped** [comment]
[latest.log](https://github.com/ThreeTAG/Palladium/files/14653708/latest.log)

The only installed mods are Mini Tardis, Palladium, Fabric API, and JEI

**Comment by GrayStriped** [comment]
> Does that happen with just Palladium? Based on testing I did, it was that one KubeJS dependency that caused it.

The problem persists without KubeJS

**Comment by Lucraft** [comment]
This issue comes from Mini Tardis, well, their lib mod.
They add "silly hears" model parts to all player models, and when it cant be found in Palladium's models it causes issues. Would be something that they have to fix/change.
https://github.com/enjarai/cicada-lib/blob/master/src/main/java/nl/enjarai/cicada/mixin/PlayerEntityModelMixin.java

**Comment by enjarai** [comment]
I can tell that that's the root cause here, but why is adding a modelpart problematic for your library, and how would I work around that? The way I'm adding the modelpart should be exactly the same as how vanilla does it, or am I missing something here?

**Comment by Lucraft** [comment]
I think you could try adding a try-catch block around the "root.getChild()" method-calls, and then consider the sillyHairsLeft/-Right fields null in the further code.
The problem is that you mixin into the vanilla player model, so every mod that will use this class and provide a fully-custom model-layer to it will crash, since their model-layer doesnt have those parts in them

**Comment by enjarai** [comment]
Hmm I see, that seems like a good approach, I'll implement that soon™. Thanks for helping figure this out, I was honestly quite confused.
