### ISSUE TITLE
Emitters?

### ISSUE THREAD

**Issue by Herocraft735** [ThreeTAG/Palladium#125]
I'm just not sure how emitters work in the particles. I checked the abilities in documentation, the particles themselves work fine ingame but the emitter itself just sticks the particles to whatever body part of the player I choose? is there any way to fix this because I also checked the wiki like it says to in the abilities and there's nothing there.

**Comment by Herocraft735** [comment]
To expand on this I mean the particles don't move at all. I set the motion to like 40 in each direction and it doesn't work.
[dust.json](https://github.com/user-attachments/files/16640556/dust.json)
This is my emitter incase it's just a me issue lmao.

**Comment by ThePhantomPig791** [comment]
unfortunately dust particles (i'm assuming you're using them because of the emitter name) can't have velocity like most particles - try it with a different particle type
if you want to have an emitter that still looks like dust but with velocity you can make a custom particle type that has movement physics and copy the textures for the decaying dust (and tint it to be the color you want)
also, for support you can join the threetag discord because you'll get answers faster and it lets the issues tab be more organized with only bug reports or feature requests

**Comment by Herocraft735** [comment]
I did use a custom particle, I figured out the issue lmao I just accidentally set the physics to false and spent like an hour trying to figure out what it was.
